namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_SUPABASE_URL: string
    NEXT_PUBLIC_SUPABASE_ANON_KEY: string
    NEXT_PUBLIC_USDC_CONTRACT_ADDRESS: string
    NEXT_PUBLIC_AGENT_WALLET_ID: string
    NEXT_PUBLIC_AGENT_WALLET_ADDRESS: string
    SUPABASE_SERVICE_ROLE_KEY: string
    CIRCLE_API_KEY: string
    CIRCLE_ENTITY_SECRET: string
    CIRCLE_BLOCKCHAIN: string
    GOOGLE_CLIENT_ID: string
    GOOGLE_CLIENT_SECRET: string
    OPENAI_API_KEY: string
    OPENAI_ASSISTANT_ID: string
  }
}